- platform: template
  sensors:
      wii:
        friendly_name: 'Wii'
        value_template: "{{ 'Online' if is_state('device_tracker.wii', 'home') else 'Offline' }}"

      tablotv:
        friendly_name: 'Tablo TV'
        value_template: "{{ 'Online' if is_state('device_tracker.tablotv', 'home') else 'Offline' }}"

      actiontechap:
        friendly_name: 'ActionTech AP'
        value_template: "{{ 'Online' if is_state('device_tracker.actiontechap', 'home') else 'Offline' }}"

      cisco_ap:
        friendly_name: 'Cisco Main AP'
        value_template: "{{ 'Online' if is_state('device_tracker.cisco_ap', 'home') else 'Offline' }}"

      trendnetap:
        friendly_name: 'TrendNet AP'
        value_template: "{{ 'Online' if is_state('device_tracker.trendnetap', 'home') else 'Offline' }}"


      unifi_ap:
        friendly_name: 'Unifi AP'
        value_template: "{{ 'Online' if is_state('device_tracker.unifi_ap', 'home') else 'Offline' }}"


      hue_hub_1:
        friendly_name: 'Hue Hub 1'
        value_template: "{{ 'Online' if is_state('device_tracker.hue_hub_1', 'home') else 'Offline' }}"

      hue_hub_2:
        friendly_name: 'Hue Hub 2'
        value_template: "{{ 'Online' if is_state('device_tracker.hue_hub_2', 'home') else 'Offline' }}"

      alexa_echo:
        friendly_name: 'Alexa Echo'
        value_template: "{{ 'Online' if is_state('device_tracker.alexa_echo', 'home') else 'Offline' }}"

      amazon_dot:
        friendly_name: 'Amazon Dot'
        value_template: "{{ 'Online' if is_state('device_tracker.amazon_dot', 'home') else 'Offline' }}"

      amazon_fire_stick:
        friendly_name: 'Amazon Fire Stick'
        value_template: "{{ 'Online' if is_state('device_tracker.amazon_fire_stick', 'home') else 'Offline' }}"

      printer:
        friendly_name: 'Printer'
        value_template: "{{ 'Online' if is_state('device_tracker.printer', 'home') else 'Offline' }}"

      circle:
        friendly_name: 'Disney Circle'
        value_template: "{{ 'Online' if is_state('device_tracker.circle', 'home') else 'Offline' }}"

      nest_downstairs:
        friendly_name: 'Downstairs Nest'
        value_template: "{{ 'Online' if is_state('device_tracker.nest_downstairs', 'home') else 'Offline' }}"

      nest_upstairs:
        friendly_name: 'Upstairs Nest'
        value_template: "{{ 'Online' if is_state('device_tracker.nest_upstairs', 'home') else 'Offline' }}"

      rachio:
        friendly_name: 'Rachio Sprinklers'
        value_template: "{{ 'Online' if is_state('device_tracker.rachio', 'home') else 'Offline' }}"

      skybell:
        friendly_name: 'Skybell Doorbell'
        value_template: "{{ 'Online' if is_state('device_tracker.skybell', 'home') else 'Offline' }}"

      samsungtv:
        friendly_name: 'Samsung TV'
        value_template: "{{ 'Online' if is_state('device_tracker.samsungtv', 'home') else 'Offline' }}"

      chromecast_audio_1:
        friendly_name: 'ChromeCast Audio 1'
        value_template: "{{ 'Online' if is_state('device_tracker.chromecast_audio_1', 'home') else 'Offline' }}"

      chromecast_audio_2:
        friendly_name: 'ChromeCast Audio 2'
        value_template: "{{ 'Online' if is_state('device_tracker.chromecast_audio_2', 'home') else 'Offline' }}"

      large_garage:
        friendly_name: 'Large Garage'
        value_template: "{{ 'Online' if is_state('device_tracker.large_garage', 'home') else 'Offline' }}"

      small_garage:
        friendly_name: 'Small Garage'
        value_template: "{{ 'Online' if is_state('device_tracker.small_garage', 'home') else 'Offline' }}"

      rgb_led_outdoor_den:
        friendly_name: 'RGB LED Outdoor Den'
        value_template: "{{ 'Online' if is_state('device_tracker.rgb_led_outdoor_den', 'home') else 'Offline' }}"

      rgb_led_garage_large:
        friendly_name: 'RGB LED Garage Large'
        value_template: "{{ 'Online' if is_state('device_tracker.rgb_led_garage_large', 'home') else 'Offline' }}"

      rgb_led_garage_small:
        friendly_name: 'RGB LED Garage Small'
        value_template: "{{ 'Online' if is_state('device_tracker.rgb_led_garage_small', 'home') else 'Offline' }}"

      smart_water_meter:
        friendly_name: 'Smart Water Meter'
        value_template: "{{ 'Online' if is_state('device_tracker.smart_water_meter', 'home') else 'Offline' }}"

      sleep_number_bed:
        friendly_name: 'Sleep Number Bed'
        value_template: "{{ 'Online' if is_state('device_tracker.sleep_number_bed', 'home') else 'Offline' }}"

      withings_scale:
        friendly_name: 'WiThings Scale'
        value_template: "{{ 'Online' if is_state('device_tracker.withings_scale', 'home') else 'Offline' }}"

      linen_door:
        friendly_name: 'Linen Door'
        value_template: "{{ 'Opened' if is_state('binary_sensor.aeotec_dsb04100_doorwindow_sensor_sensor_4_0', 'on') else 'Closed' }}"
