#-------------------------------------------
#  Fire Tablet Alarm Panel -
#  http://www.vmwareinfo.com/2017/07/visualizing-smart-home-using-home.html
#-------------------------------------------
#
homeassistant:
  customize_glob:
    "sensor.alarm_panel_*":
      emulated_hue: False
      hidden: False

media_player:
  - platform: tts_floorplan_speaker
    name: Alarm Panel 1

  - platform: tts_floorplan_speaker
    name: Alarm Panel 2

#---Sensors for Fire Tablet-----------------------------

binary_sensor:

  - platform: mqtt
    state_topic: floorplan/alarm_panel_1
    name: Bedroom Alarm Panel
    retain: true

  - platform: mqtt
    state_topic: floorplan/alarm_panel_2
    name: Entry Alarm Panel
    retain: true
