#-------------------------------------------
#  Fire Tablet Alarm Panel - http://www.vmwareinfo.com/2017/07/visualizing-smart-home-using-home.html
#-------------------------------------------
#
# homeassistant:
#   customize:
#     binary_sensor.office_motion:
#       icon: mdi:sensor
#       friendly_name: Office Motion Sensor
#       emulated_hue: False
#       hidden: False

#---Sensor for Fire Tablet-----------------------------
sensor:
  - platform: mqtt
    state_topic: "wallpanel/alarm 1/sensor/battery"
    name: "Alarm Panel 1 Battery Level"
    value_template: '{{ value_json.value }}'
    unit_of_measurement: '%'
    device_class: power

  - platform: mqtt
    state_topic: "wallpanel/alarm 1/sensor/battery"
    name: "Alarm Panel 1 Plugged In"
    value_template: '{{ value_json.acPlugged }}'
    unit_of_measurement: '%'
    device_class: power

  - platform: mqtt
    state_topic: "wallpanel/alarm 1/sensor/motion"
    name: "Alarm Panel 1 Motion"
    value_template: '{{ value_json.value }}'
    device_class: motion

  - platform: mqtt
    state_topic: "wallpanel/alarm 1/state"
    name: "Alarm Panel 1 Screen"
    value_template: '{{ value_json.screenOn }}'
