#-------------------------------------------
#  Bruh Light Sensor Related Packages
#-------------------------------------------
#------LightSensor Node---http://amzn.to/2oUgj5i
homeassistant:
  customize:
    binary_sensor.office_motion:
      icon: mdi:sensor
      friendly_name: Office Motion Sensor
      emulated_hue: False
      hidden: False
#---Sensor for Light-----------------------------
binary_sensor:
  - platform: mqtt
    state_topic: "NodeMCU4/Motion/Motion"
    name: "Office_Motion"
    payload_on: 1
    payload_off: 0
    device_class: motion

automation:
  - alias: 'Motion in the Office - Turn on Light'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.office_motion
        to: 'on'
        from: 'off'

    action:
      - service: light.turn_on
        entity_id: light.office

  - alias: 'Motion in the Office - Turn off Light'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.office_motion
        to: 'off'
        from: 'on'
        for:
          minutes: 3

    action:
      - service: light.turn_off
        entity_id: light.office
